=== Perry3Dnl/Unclaimable/data/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/Perry3Dnl/Unclaimable/data/schema.json",
  "title": "Unclaimable reserved-name list",
  "type": "object",
  "additionalProperties": false,
  "required": ["schema", "category", "description", "values"],
  "properties": {
    "schema": {
      "const": 1
    },
    "category": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "minLength": 1
    },
    "values": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "uniqueItems": true
    }
  }
}

=== Perry3Dnl/Unclaimable/platforms/dotnet/src/Unclaimable.Extended/Data/fiction.json
{
  "schema": 1,
  "category": "fiction",
  "description": "Fictional characters and franchises.",
  "values": [
    "Agent 47",
    "Ahsoka Tano",
    "Akira Fudo",
    "Aladdin",
    "Albus Dumbledore",
    "Alice in Wonderland",
    "Alucard",
    "Amy Rose",
    "Anakin Skywalker",
    "Android 18",
    "Anna",
    "Aqua",
    "Aquaman",
    "Aragorn",
    "Ariel",
    "Arthur Dent",
    "Arthur Morgan",
    "Arya Stark",
    "Ash Ketchum",
    "Aslan",
    "Astarion",
    "Asterix",
    "Astro Boy",
    "Atreus",
    "Azula",
    "Bane",
    "Barbie",
    "Bart Simpson",
    "Batman",
    "Baymax",
    "Beetlejuice",
    "Bender Bending Rodriguez",
    "Big Boss",
    "Bilbo Baggins",
    "Black Panther",
    "Black Widow",
    "Blastoise",
    "Blossom",
    "Boba Fett",
    "Bojack Horseman",
    "Boromir",
    "Bowser",
    "Bruce Banner",
    "Bruce Wayne",
    "Bugs Bunny",
    "Bulma",
    "Buzz Lightyear",
    "C-3PO",
    "Captain America",
    "Captain Hook",
    "Captain Marvel",
    "Captain Price",
    "Captain Rex",
    "Carl Grimes",
    "Carl Johnson",
    "Carmen Sandiego",
    "Catwoman",
    "Chell",
    "Chewbacca",
    "Chun-Li",
    "Cinderella",
    "Ciri",
    "Clementine",
    "Clifford the Big Red Dog",
    "Cloud Strife",
    "Commander Cody",
    "Commander Shepard",
    "Corvo Attano",
    "Crash Bandicoot",
    "Cruella de Vil",
    "Daenerys Targaryen",
    "Daffy Duck",
    "Daphne Blake",
    "Daredevil",
    "Darth Maul",
    "Darth Sidious",
    "Darth Vader",
    "Daryl Dixon",
    "Davy Jones",
    "Deadpool",
    "Deathstroke",
    "Denji",
    "Dexter Morgan",
    "Dio Brando",
    "Doctor Doom",
    "Doctor Octopus",
    "Doctor Strange",
    "Donald Duck",
    "Donatello",
    "Donkey Kong",
    "Doom Slayer",
    "Dora the Explorer",
    "Dr Eggman",
    "Dr Emmett Brown",
    "Dr Watson",
    "Draco Malfoy",
    "Dracula",
    "Duke Nukem",
    "Edward Elric",
    "Eeyore",
    "Eleven",
    "Ellie Williams",
    "Elsa",
    "Eren Yeager",
    "Eric Cartman",
    "Ethan Hunt",
    "Ezio Auditore",
    "Faramir",
    "Faye Valentine",
    "Felix the Cat",
    "Finn the Human",
    "Fluttershy",
    "Forrest Gump",
    "Frank Castle",
    "Franklin Clinton",
    "Freddy Krueger",
    "Frieza",
    "Frodo Baggins",
    "Gandalf",
    "Ganondorf",
    "Garrus Vakarian",
    "Geralt of Rivia",
    "Ghostface",
    "GLaDOS",
    "Gohan",
    "Goku",
    "Gollum",
    "Goofy",
    "Gordon Freeman",
    "Griffith",
    "Grogu",
    "Groot",
    "Gru",
    "Guts",
    "Gwen Stacy",
    "Hades",
    "Hagrid",
    "Han Solo",
    "Hank Hill",
    "Hannibal Lecter",
    "Harley Quinn",
    "Harry Potter",
    "Harvey Dent",
    "Hatsune Miku",
    "He-Man",
    "Hello Kitty",
    "Hercule Poirot",
    "Hermione Granger",
    "Hiccup Haddock",
    "Hinata Hyuga",
    "Homelander",
    "Homer Simpson",
    "Hulk",
    "Ichigo Kurosaki",
    "Indiana Jones",
    "Inuyasha",
    "Iron Man",
    "Isabelle",
    "Jack Skellington",
    "Jack Sparrow",
    "Jade",
    "Jake the Dog",
    "James Bond",
    "Jason Voorhees",
    "Jean Grey",
    "Jean-Luc Picard",
    "Jesse Pinkman",
    "Jill Valentine",
    "Jimmy Neutron",
    "Jinx",
    "Joel Miller",
    "John Constantine",
    "John Marston",
    "John Wick",
    "Johnny Bravo",
    "Johnny Cage",
    "Johnny Silverhand",
    "Joker",
    "Jon Snow",
    "Joseph Joestar",
    "Jotaro Kujo",
    "Judy Hopps",
    "Kakashi Hatake",
    "Katniss Everdeen",
    "Ken Masters",
    "Kenny McCormick",
    "Kiki",
    "King Dedede",
    "King Kong",
    "Kirby",
    "Klaus Hargreeves",
    "Knuckles the Echidna",
    "Korra",
    "Kratos",
    "Kuromi",
    "Kuzco",
    "Kylo Ren",
    "Lara Croft",
    "Legolas",
    "Leia Organa",
    "Lelouch Lamperouge",
    "Leon Kennedy",
    "Lester Crest",
    "Levi Ackerman",
    "Lex Luthor",
    "Light Yagami",
    "Lightning McQueen",
    "Lilo Pelekai",
    "Link",
    "Lisa Simpson",
    "Little Mac",
    "Loki",
    "Lucario",
    "Lucifer Morningstar",
    "Luffy",
    "Luigi",
    "Luke Skywalker",
    "Luna Lovegood",
    "Mabel Pines",
    "Mad Hatter",
    "Magneto",
    "Mai Shiranui",
    "Majin Buu",
    "Makima",
    "Malenia",
    "Mandalorian",
    "Marge Simpson",
    "Mario",
    "Master Chief",
    "Master Roshi",
    "Meg Griffin",
    "Megamind",
    "Megatron",
    "Michael De Santa",
    "Mickey Mouse",
    "Mikasa Ackerman",
    "Miles Morales",
    "Minato Namikaze",
    "Minnie Mouse",
    "Mister Fantastic",
    "Monkey D Luffy",
    "Mordecai",
    "Morticia Addams",
    "Morty Smith",
    "Mr Bean",
    "Mr Burns",
    "Mr Krabs",
    "Ms Marvel",
    "Mufasa",
    "Mulan",
    "Nami",
    "Naruto Uzumaki",
    "Nathan Drake",
    "Ned Flanders",
    "Ned Stark",
    "Neo",
    "Nico Robin",
    "Niko Bellic",
    "Nobara Kugisaki",
    "Obi-Wan Kenobi",
    "Olaf",
    "Optimus Prime",
    "Orochimaru",
    "Paddington Bear",
    "Palpatine",
    "Papu Papu",
    "Patrick Star",
    "Pennywise",
    "Peppa Pig",
    "Percy Jackson",
    "Perry the Platypus",
    "Peter Griffin",
    "Peter Parker",
    "Peter Rabbit",
    "Phoenix Wright",
    "Pikachu",
    "Po",
    "Popeye",
    "Princess Bubblegum",
    "Princess Daisy",
    "Princess Mononoke",
    "Princess Peach",
    "Princess Zelda",
    "Professor Oak",
    "Professor X",
    "R2-D2",
    "Ragnar Lothbrok",
    "Rambo",
    "Rapunzel",
    "Rei Ayanami",
    "Rem",
    "Remy",
    "Rick Grimes",
    "Rick Sanchez",
    "Robin",
    "Rocky Balboa",
    "Ron Weasley",
    "Roronoa Zoro",
    "Rosalina",
    "Ryu",
    "Saitama",
    "Sakura Haruno",
    "Sam Fisher",
    "Samwise Gamgee",
    "Sarah Connor",
    "Sasuke Uchiha",
    "Saul Goodman",
    "Sauron",
    "Scarlet Witch",
    "Scooby-Doo",
    "Scorpion",
    "Sephiroth",
    "Severus Snape",
    "Shaggy Rogers",
    "Sherlock Holmes",
    "Shinji Ikari",
    "Shoto Todoroki",
    "Shrek",
    "Simba",
    "Sirius Black",
    "Skeletor",
    "Snow White",
    "Sokka",
    "Solid Snake",
    "Solidus Snake",
    "Son Gohan",
    "Son Goku",
    "Sonic the Hedgehog",
    "Sora",
    "Spawn",
    "Spider-Man",
    "SpongeBob SquarePants",
    "Squidward Tentacles",
    "Stan Marsh",
    "Star Butterfly",
    "Steve Minecraft",
    "Steve Rogers",
    "Steven Universe",
    "Stitch",
    "Stuart Little",
    "Sub-Zero",
    "Superman",
    "Sylvanas Windrunner",
    "Tails",
    "Tails Prower",
    "Tanjiro Kamado",
    "Tenzin",
    "Thanos",
    "The Flash",
    "The Mandalorian",
    "The Riddler",
    "Thomas Shelby",
    "Thor",
    "Thor Odinson",
    "Tifa Lockhart",
    "Tigger",
    "Timmy Turner",
    "Tom Nook",
    "Tommy Vercetti",
    "Tony Stark",
    "Toothless",
    "Trunks",
    "Tyrion Lannister",
    "Ultron",
    "Ursula",
    "Vegeta",
    "Velma Dinkley",
    "Venom",
    "Violet Parr",
    "Vision",
    "Vito Corleone",
    "Voldemort",
    "Walter White",
    "Waluigi",
    "Wario",
    "Wednesday Addams",
    "Winnie the Pooh",
    "Wolverine",
    "Wonder Woman",
    "Woody",
    "Wreck-It Ralph",
    "Yennefer of Vengerberg",
    "Yoda",
    "Yoshi",
    "Yuji Itadori",
    "Zatanna",
    "Zelda",
    "Zoro",
    "Zuko"
  ]
}

=== Perry3Dnl/Unclaimable/data/extended/publicfigures/curated/reserved.json
{
  "schema": 1,
  "category": "publicfigures",
  "description": "Curated political and public-figure identities used only as neutral protected names.",
  "values": [
    "abdel fattah el sisi",
    "abiy ahmed",
    "alexandria ocasio cortez",
    "andy burnham",
    "angela merkel",
    "anthony albanese",
    "antonio guterres",
    "barack obama",
    "benjamin netanyahu",
    "bernie sanders",
    "bill clinton",
    "bola tinubu",
    "boris johnson",
    "caroline van der plas",
    "christine lagarde",
    "christopher luxon",
    "claudia sheinbaum",
    "cyril ramaphosa",
    "david cameron",
    "dick schoof",
    "donald trump",
    "emmanuel macron",
    "felix tshisekedi",
    "ferdinand marcos jr",
    "francois hollande",
    "frans timmermans",
    "friedrich merz",
    "gavin newsom",
    "geert wilders",
    "george w bush",
    "giorgia meloni",
    "hillary clinton",
    "jair bolsonaro",
    "jd vance",
    "jens stoltenberg",
    "jerome powell",
    "joe biden",
    "john mahama",
    "joseph boakai",
    "justin trudeau",
    "kaja kallas",
    "kamala harris",
    "keir starmer",
    "lai ching te",
    "lee jae myung",
    "luiz inacio lula da silva",
    "mahmoud abbas",
    "marine le pen",
    "mark carney",
    "mark rutte",
    "matteo salvini",
    "mohammed bin salman",
    "mohammed bin zayed",
    "nana akufo addo",
    "nancy pelosi",
    "narendra modi",
    "ngozi okonjo iweala",
    "nicolas sarkozy",
    "olaf scholz",
    "paul kagame",
    "pedro sanchez",
    "peter dutton",
    "pieter omtzigt",
    "prabowo subianto",
    "rahul gandhi",
    "recep tayyip erdogan",
    "rishi sunak",
    "rob bauer",
    "rob jetten",
    "ron desantis",
    "sadiq khan",
    "samia suluhu hassan",
    "santiago abascal",
    "shigeru ishiba",
    "tamim bin hamad al thani",
    "tedros adhanom ghebreyesus",
    "theresa may",
    "ursula von der leyen",
    "vladimir putin",
    "volodymyr zelenskyy",
    "william ruto",
    "yoweri museveni"
  ]
}

=== Perry3Dnl/Unclaimable/platforms/dotnet/src/Unclaimable.Extended/Data/hatespeech.json
{
  "schema": 1,
  "category": "hatespeech",
  "description": "Curated high-confidence identity-targeting abusive usernames and hateful slogans; whole-identifier matches through Core only. This is not an exhaustive multilingual hate-speech lexicon.",
  "values": [
    "bloodandsoil",
    "chinkbasher",
    "chinkbashers",
    "chinkhater",
    "chinkhaters",
    "chinklover",
    "cripplebasher",
    "cripplehater",
    "cripplehaters",
    "death to gays",
    "death to immigrants",
    "death to muslims",
    "death tojews",
    "dykebasher",
    "dykebashers",
    "dykehater",
    "dykehaters",
    "ethniccleansing",
    "fagbasher",
    "fagbashers",
    "faggotry",
    "faghater",
    "faghaters",
    "fagkiller",
    "fagkillers",
    "faglord",
    "faglover",
    "gasalljews",
    "gookbasher",
    "gookbashers",
    "gookhater",
    "gookhaters",
    "heilhitler",
    "kikebasher",
    "kikebashers",
    "kikehater",
    "kikehaters",
    "kikelover",
    "killallgays",
    "killallimmigrants",
    "killalljews",
    "killallmuslims",
    "masterrace",
    "racepurity",
    "racialcleansing",
    "racialpurity",
    "racialsuperiority",
    "ragheadbasher",
    "ragheadhater",
    "ragheadhaters",
    "ragheadlover",
    "siegheil",
    "spicbasher",
    "spicbashers",
    "spichater",
    "spichaters",
    "spiclover",
    "towelheadbasher",
    "towelheadhater",
    "towelheadhaters",
    "trannybasher",
    "trannybashers",
    "trannyhater",
    "trannyhaters",
    "trannylover",
    "wetbackbasher",
    "wetbackhater",
    "wetbackhaters",
    "whitepowerforever"
  ]
}

=== Perry3Dnl/Unclaimable/data/extended/financial/curated/reserved.json
{
  "schema": 1,
  "category": "financial",
  "description": "Banks, insurers, payment institutions, asset managers, and other financial-service identities from many countries and regions.",
  "values": [
    "abanca",
    "absa bank",
    "adyen bank",
    "aia group",
    "akbank",
    "allstate",
    "alpha bank",
    "american express bank",
    "anz bank",
    "argenta",
    "axa",
    "banca mediolanum",
    "banca monte dei paschi di siena",
    "banco bilbao vizcaya argentaria",
    "banco do brasil",
    "banco santander",
    "bank hapoalim",
    "bank leumi",
    "bank mandiri",
    "bank millennium",
    "bank muscat",
    "bank of china",
    "bank of ireland",
    "bank of montreal",
    "bank of new york mellon",
    "bank rakyat indonesia",
    "bankia",
    "banorte",
    "bawag",
    "belfius",
    "blackrock",
    "bmo",
    "bnp paribas fortis",
    "bradesco",
    "caixa economica federal",
    "canara bank",
    "capital one bank",
    "cathay united bank",
    "charles schwab",
    "china citic bank",
    "china construction bank",
    "china merchants bank",
    "citizens bank",
    "commonwealth bank",
    "credit suisse",
    "creditas",
    "dbs bank",
    "discover bank",
    "dnb",
    "dz bank",
    "erste bank",
    "eurobank",
    "fidelity investments",
    "fifth third bank",
    "first abu dhabi bank",
    "first citizens bank",
    "franklin templeton",
    "gazprombank",
    "generali",
    "hana bank",
    "hang seng bank",
    "icbc",
    "ing bank",
    "intesa sanpaolo",
    "invesco",
    "itau unibanco",
    "jp morgan asset management",
    "julius baer",
    "kbc bank",
    "keybank",
    "klarna bank",
    "kotak mahindra bank",
    "landesbank baden wurttemberg",
    "legal and general",
    "lloyds bank",
    "manulife",
    "metlife",
    "mizuho bank",
    "morgan stanley",
    "mufg bank",
    "munich re",
    "national australia bank",
    "national bank of canada",
    "nationwide building society",
    "natwest",
    "nordea bank",
    "northern trust",
    "ocbc bank",
    "otp bank",
    "paypal payments",
    "pimco",
    "pnc bank",
    "prudential financial",
    "raiffeisen bank",
    "revolut bank",
    "royal bank of canada",
    "royal bank of scotland",
    "schroders",
    "scotiabank",
    "seb bank",
    "shinhan bank",
    "societe generale",
    "standard bank",
    "standard chartered",
    "state bank of india",
    "state street",
    "stripe payments",
    "sumitomo mitsui banking corporation",
    "sun life",
    "swedbank",
    "swiss re",
    "t rowe price",
    "td bank",
    "travelers",
    "truist",
    "ubs bank",
    "unicredit bank",
    "uob",
    "us bank",
    "vanguard",
    "virgin money",
    "visa europe",
    "wells fargo bank",
    "westpac",
    "wise payments",
    "worldline",
    "yes bank",
    "zurich cantonal bank"
  ]
}

=== Perry3Dnl/Unclaimable/data/extended/fiction/curated/reserved.json
{
  "schema": 1,
  "category": "fiction",
  "description": "Fictional character identities from literature, film, television, comics, animation, and games.",
  "values": [
    "ahsoka tano",
    "albus dumbledore",
    "anakin skywalker",
    "aragorn",
    "arthur dent",
    "ash ketchum",
    "asterix",
    "atreus",
    "bart simpson",
    "batman",
    "bilbo baggins",
    "black panther",
    "black widow",
    "bojack horseman",
    "bowser",
    "bruce banner",
    "bruce wayne",
    "bugs bunny",
    "captain america",
    "cersei lannister",
    "chandler bing",
    "charizard",
    "ciri",
    "clark kent",
    "cortana",
    "daenerys targaryen",
    "daffy duck",
    "darth vader",
    "daryl dixon",
    "deadpool",
    "dexter morgan",
    "diana prince",
    "din djarin",
    "doctor strange",
    "don draper",
    "donald duck",
    "doom slayer",
    "dwight schrute",
    "eleven hopper",
    "frodo baggins",
    "gandalf",
    "ganondorf",
    "geralt of rivia",
    "gimli",
    "gollum",
    "goofy",
    "grogu",
    "han solo",
    "hannibal lecter",
    "harry potter",
    "hermione granger",
    "homer simpson",
    "hulk",
    "indiana jones",
    "iron man",
    "james bond",
    "jesse pinkman",
    "joey tribbiani",
    "john rambo",
    "john watson",
    "jon snow",
    "kratos",
    "lara croft",
    "legolas",
    "leia organa",
    "link",
    "lisa simpson",
    "logan howlett",
    "loki laufeyson",
    "luigi",
    "luke skywalker",
    "magneto",
    "marge simpson",
    "mario",
    "master chief",
    "michael scott",
    "mickey mouse",
    "miles tails prower",
    "minnie mouse",
    "monica geller",
    "morty smith",
    "natasha romanoff",
    "nathan drake",
    "ned stark",
    "obi wan kenobi",
    "palpatine",
    "patrick star",
    "peter griffin",
    "peter parker",
    "phoebe buffay",
    "pikachu",
    "princess peach",
    "princess zelda",
    "professor x",
    "rachel green",
    "rick grimes",
    "rick sanchez",
    "rocky balboa",
    "ron weasley",
    "ross geller",
    "samus aran",
    "saul goodman",
    "sauron",
    "scooby doo",
    "severus snape",
    "shadow the hedgehog",
    "shaggy rogers",
    "sherlock holmes",
    "solid snake",
    "sonic the hedgehog",
    "spider man",
    "spongebob squarepants",
    "stephen strange",
    "steve rogers",
    "superman",
    "tchalla",
    "ted lasso",
    "thor odinson",
    "tony soprano",
    "tony stark",
    "triss merigold",
    "tyrion lannister",
    "voldemort",
    "wade wilson",
    "walter white",
    "wednesday addams",
    "wolverine",
    "wonder woman",
    "yennefer",
    "yoda"
  ]
}

=== Perry3Dnl/Unclaimable/platforms/dotnet/src/Unclaimable.Extended/Data/crypto.json
{
  "schema": 1,
  "category": "crypto",
  "description": "Cryptocurrency, blockchain and decentralized-finance project names.",
  "values": [
    "1inch",
    "Akash Network",
    "Algorand",
    "ApeCoin",
    "Aptos",
    "Arbitrum",
    "Arweave",
    "Astar",
    "Avalanche",
    "Axie Infinity",
    "Basic Attention Token",
    "Bitcoin",
    "Bitcoin Cash",
    "Bitget Token",
    "Bittensor",
    "Blur",
    "Cardano",
    "Celestia",
    "Celo",
    "Chiliz",
    "Compound",
    "Conflux",
    "Core DAO",
    "Cosmos",
    "Curve DAO",
    "Dash",
    "Decentraland",
    "Decred",
    "Dogecoin",
    "Enjin Coin",
    "EOS",
    "Ethereum",
    "Ethereum Classic",
    "Fantom",
    "Fetch.ai",
    "Filecoin",
    "Flow",
    "Gala",
    "GateToken",
    "Gnosis",
    "Harmony",
    "Hedera",
    "Helium",
    "Illuvium",
    "Immutable",
    "Injective",
    "Internet Computer",
    "IOTA",
    "Jupiter",
    "Kaia",
    "Kaspa",
    "Kava",
    "KuCoin Token",
    "Kusama",
    "Lido DAO",
    "Litecoin",
    "Loopring",
    "Maker",
    "Mantle",
    "Mina Protocol",
    "Monero",
    "Moonbeam",
    "Moonriver",
    "MultiversX",
    "Near Protocol",
    "Nexo",
    "Ocean Protocol",
    "OKB",
    "Ondo",
    "Ontology",
    "Optimism",
    "Ordinals",
    "Pendle",
    "Polkadot",
    "Pyth Network",
    "Quant",
    "Ravencoin",
    "Safe",
    "Shiba Inu",
    "SingularityNET",
    "Solana",
    "Stacks",
    "Stellar",
    "Tether",
    "Tezos",
    "The Graph",
    "The Sandbox",
    "Theta Network",
    "THORChain",
    "Toncoin",
    "VeChain",
    "Waves",
    "Worldcoin",
    "Zcash",
    "Zilliqa"
  ]
}

=== Perry3Dnl/Unclaimable/data/profanity/reserved.json
{
  "schema": 1,
  "category": "profanity",
  "description": "Common English profanity and vulgar insults. This category is opt-in and intentionally excludes identity-targeting slurs.",
  "values": [
    "arse",
    "arsehole",
    "ass",
    "assclown",
    "assface",
    "asshat",
    "asshole",
    "asslicker",
    "asswipe",
    "bastard",
    "bitch",
    "bitchass",
    "bitches",
    "bitchface",
    "bitchy",
    "bollock",
    "bollocks",
    "bullshit",
    "bullshitter",
    "bullshitting",
    "bugger",
    "cock",
    "cockface",
    "cockhead",
    "cockmuncher",
    "cocksucker",
    "crap",
    "craphead",
    "crappy",
    "cunt",
    "cuntface",
    "dammit",
    "damn",
    "dick",
    "dickbag",
    "dickface",
    "dickhead",
    "dickwad",
    "dickweed",
    "dipshit",
    "douche",
    "douchebag",
    "dumbass",
    "fuck",
    "fuckass",
    "fucked",
    "fucker",
    "fuckers",
    "fuckface",
    "fuckhead",
    "fucking",
    "fuckoff",
    "fuckup",
    "fuckwad",
    "fuckwit",
    "goddamn",
    "goddammit",
    "horseshit",
    "jackass",
    "jackasses",
    "motherfucker",
    "motherfuckers",
    "motherfucking",
    "piss",
    "pissed",
    "pisser",
    "pissoff",
    "prick",
    "prickhead",
    "pussy",
    "shit",
    "shitass",
    "shitbag",
    "shitface",
    "shithead",
    "shitshow",
    "shitstorm",
    "shitty",
    "sonofabitch",
    "suckmyass",
    "suckmydick",
    "twat",
    "twatface",
    "wank",
    "wanker",
    "wankers",
    "wanking",
    "whore",
    "whorebag",
    "slut",
    "slutty",
    "skank",
    "skanky",
    "tosser",
    "bellend",
    "knobhead",
    "shitforbrains",
    "fucknugget",
    "fuckstick",
    "shitstain",
    "assmunch",
    "assmuncher",
    "buttfuck",
    "buttfucker",
    "clusterfuck",
    "dickless",
    "shitfuck",
    "shitwit",
    "wankstain"
  ]
}

=== Perry3Dnl/Unclaimable/data/extended/regionalprofanity/curated/reserved.json
{
  "schema": 1,
  "category": "regionalprofanity",
  "description": "Additional regional slang, insults, and profanity across multiple languages.",
  "values": [
    "abruti",
    "amk",
    "anjing",
    "arschloch",
    "arsehole",
    "bangsat",
    "bastardo",
    "bellend",
    "berk",
    "bloody idiot",
    "bollocks",
    "bugger off",
    "buoi",
    "cabron",
    "capullo",
    "cazzo",
    "chav",
    "chuj",
    "coglione",
    "cojones",
    "con cac",
    "connard",
    "connasse",
    "couillon",
    "dickhead",
    "dit me",
    "du ma",
    "dummkopf",
    "dupek",
    "eikel",
    "encule",
    "figlio di puttana",
    "fotze",
    "fuckwit",
    "gerizekali",
    "gilipollas",
    "goblok",
    "hijoputa",
    "hoerenzoon",
    "hostia puta",
    "hufter",
    "hurensohn",
    "imbecil",
    "jebac",
    "kankerlijer",
    "klootzak",
    "knobhead",
    "kontol",
    "kurwa",
    "kutvent",
    "kutwijf",
    "lul",
    "mat day",
    "memek",
    "merdeux",
    "minger",
    "mistkerl",
    "mof",
    "mongool",
    "ngentot",
    "numpty",
    "orospu cocugu",
    "pendejo",
    "pezevenk",
    "pillock",
    "pizda",
    "plonker",
    "prat",
    "putain",
    "puto",
    "salaud",
    "salope",
    "scheisskerl",
    "schele",
    "schlampe",
    "shithead",
    "siktir",
    "skurwysyn",
    "slet",
    "stronzo",
    "sukkel",
    "teringlijer",
    "testa di cazzo",
    "tosser",
    "tyfuslijer",
    "vaffanculo",
    "vollidiot",
    "wanker",
    "wazzock",
    "wichser",
    "wijf"
  ]
}
